from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('pos.views',
    url(r'^$', 'index'),
    url(r'^index.html$', 'index'),
    url(r'^login.html$', 'login'),
    url(r'^logout.html$', 'logout'),
    url(r'^filtereduserlist$', 'filtereduserlist'),
    url(r'^userlist.html$', 'userlist'),
    url(r'^newUser.html$', 'newUser'),
    url(r'^buyLine.html$', 'buyLine'),
    url(r'^noCredit.html$', 'noCredit'),
    url(r'^user/$', 'user'),
    url(r'^user/barcode$', 'get_user_by_barcode'),
    url(r'^user/purchases$', 'purchaselist'),
    url(r'^user/purchase$', 'purchase'),
    url(r'^user/purchaseli$', 'purchase'),
    url(r'^user/undodialog$', 'undo_dialog'),
    url(r'^user/activate$', 'admin_user_activate'),
    url(r'^user/deactivate$', 'admin_user_deactivate'),
    url(r'^user/new$', 'new_user'),
    url(r'^user/edit$', 'edit_user'),
    url(r'^purchase$', 'transaction'),
    url(r'^passcode$', 'passcode'),

    url(r'^admin.html$', 'admin'),
    url(r'^adminuserlist.html', 'admin_user_list'),
    url(r'^adminoptions$', 'admin_user_options'),
    url(r'^admin_edit_user', 'admin_edit_user'),
)
